"""Core data structures for the GraphBot execution engine."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class TaskStatus(str, Enum):
    CREATED = "created"
    BLOCKED = "blocked"
    READY = "ready"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class FlowType(str, Enum):
    PARALLEL = "parallel"
    SEQUENCE = "sequence"
    FALLBACK = "fallback"


class Domain(str, Enum):
    FILE = "file"
    WEB = "web"
    CODE = "code"
    COMMS = "comms"
    SYSTEM = "system"
    SYNTHESIS = "synthesis"


@dataclass
class TaskNode:
    """The universal unit of work in the GraphBot execution engine.

    Every task -- whether a single leaf operation or a complex multi-level tree --
    is represented as a TaskNode. Nodes declare typed data contracts via `provides`
    and `consumes` fields, enabling zero-copy data forwarding between dependent nodes.

    TaskNode is intentionally mutable: it tracks execution state (status, output,
    timing) that changes during pipeline processing. For safe concurrent reads,
    use snapshot() to get a frozen copy.
    """

    id: str
    description: str
    parent_id: str | None = None
    children: list[str] = field(default_factory=list)

    # Dependency contracts (typed data flow)
    requires: list[str] = field(default_factory=list)
    provides: list[str] = field(default_factory=list)
    consumes: list[str] = field(default_factory=list)

    # Execution parameters
    is_atomic: bool = False
    domain: Domain = Domain.SYNTHESIS
    complexity: int = 1
    flow_type: FlowType = FlowType.PARALLEL
    model: str | None = None
    status: TaskStatus = TaskStatus.CREATED

    # Data flow
    context: str = ""
    input_data: dict[str, Any] = field(default_factory=dict)
    output_data: dict[str, Any] = field(default_factory=dict)

    # Tool routing (Phase 11)
    tool_method: str | None = None
    tool_params: dict[str, str] = field(default_factory=dict)

    # Metadata
    created_at: datetime = field(default_factory=datetime.now)
    completed_at: datetime | None = None
    tokens_used: int = 0
    latency_ms: float = 0.0
    error: str | None = None


@dataclass(frozen=True)
class CompletionResult:
    """Result from a single LLM completion call."""

    content: str
    model: str
    tokens_in: int
    tokens_out: int
    latency_ms: float
    cost: float


@dataclass(frozen=True)
class ExecutionResult:
    """Result from executing a task tree. Frozen for safe concurrent reads."""

    root_id: str
    output: str
    success: bool
    total_nodes: int = 0
    total_tokens: int = 0
    total_latency_ms: float = 0.0
    total_cost: float = 0.0
    context_tokens: int = 0
    model_used: str = ""
    tools_used: int = 0
    llm_calls: int = 0
    nodes: tuple[str, ...] = ()
    errors: tuple[str, ...] = ()


@dataclass(frozen=True)
class Reflection:
    """Structured failure analysis from a failed task execution.

    Generated by the reflection engine after a task fails. Stored as a Memory
    node in the knowledge graph for future retrieval during decomposition.
    """

    what_failed: str
    why: str
    what_to_try: str


@dataclass(frozen=True)
class Pattern:
    """A reusable execution tree template extracted from completed tasks."""

    id: str
    trigger: str
    description: str
    variable_slots: tuple[str, ...] = ()
    tree_template: str = ""
    success_count: int = 0
    failure_count: int = 0
    avg_tokens: float = 0.0
    avg_latency_ms: float = 0.0
    created_at: datetime = field(default_factory=datetime.now)
    last_used: datetime | None = None


@dataclass(frozen=True)
class GraphContext:
    """Compact context assembled from the knowledge graph for a specific task.
    Frozen for safe concurrent reads across parallel task execution.
    """

    user_summary: str = ""
    relevant_entities: tuple[dict[str, str], ...] = ()
    active_memories: tuple[str, ...] = ()
    matching_patterns: tuple[Pattern, ...] = ()
    total_tokens: int = 0
    token_count: int = 0

    def format(self) -> str:
        """Format context as a compact string for prompt injection."""
        parts: list[str] = []
        if self.user_summary:
            parts.append(f"USER: {self.user_summary}")
        for entity in self.relevant_entities:
            label = entity.get("type", "ENTITY")
            name = entity.get("name", "unknown")
            details = entity.get("details", "")
            parts.append(f"{label}: {name} | {details}")
        for memory in self.active_memories:
            parts.append(f"MEMORY: {memory}")
        for pattern in self.matching_patterns:
            parts.append(
                f"PATTERN: \"{pattern.trigger}\" available "
                f"({pattern.success_count} successes, avg {pattern.avg_tokens:.0f} tokens)"
            )
        return "\n".join(parts)
